name: tts-voices-info
services:
  - name: web
    github:
      repo: AceCentre/Correct-A-Sentence
      branch: main
    image: python:3.11.4  # Use the appropriate base image
    build_command: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
      python create_google_creds.py
    run_command: |
      python main.py
    environment:
      GOOGLE_CREDS_JSON: ${GOOGLE_CREDS_JSON}  # Ensure this is set in your DigitalOcean app settings
    source_dir: .  # Make sure this points to your application's source directory
    envs:
      - key: GOOGLE_CREDS_JSON
        value: ${GOOGLE_CREDS_JSON}
    buildpacks:
      - digitalocean/python-appdetect
      - heroku/python
      - digitalocean/procfile
      - digitalocean/custom

static_sites: []
jobs: []
databases: []
